name: Calling finish-release-dir action

on:
  push:
    branches:
      - main

jobs:
  composite_example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Call the reusable workflow (composite action)
      - name: Call finish-release-dir composite action
        uses: aqeeleurus/finish-release-dir/github/workflows/blank.yml@main
        with:
          branch-name: test
          merge-to-branch-name: main
          token: ${{ secrets.CUSTOM_PAT }}
